"""empty message

Revision ID: 16f6c1ce2c5b
Revises: 8396b6d3376e
Create Date: 2024-03-02 14:16:37.538522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16f6c1ce2c5b'
down_revision = '8396b6d3376e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('avatar_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
