"""empty message

Revision ID: 296f14803f6f
Revises: 
Create Date: 2023-08-31 22:26:18.582305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '296f14803f6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_list_association', schema=None) as batch_op:
        batch_op.alter_column('book_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('list_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_timestamp'))

    with op.batch_alter_table('book_list_association', schema=None) as batch_op:
        batch_op.alter_column('list_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('book_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
