"""empty message

Revision ID: 3f0656ed7dee
Revises: 8dae48e48bb9
Create Date: 2023-12-03 00:33:25.463744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f0656ed7dee'
down_revision = '8dae48e48bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_date', sa.Date(), nullable=True))
        batch_op.drop_column('publication_year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_year', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('published_date')

    # ### end Alembic commands ###
