"""empty message

Revision ID: 4569696d1816
Revises: 701b394e604f
Create Date: 2023-11-12 22:46:46.561372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4569696d1816'
down_revision = '701b394e604f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.String(length=270),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=270),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###
