"""empty message

Revision ID: a34422d45fdc
Revises: a23bd4eab976
Create Date: 2023-11-08 22:25:51.564156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a34422d45fdc'
down_revision = 'a23bd4eab976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.drop_index('google_id')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', mysql.VARCHAR(length=120), nullable=True))
        batch_op.create_index('google_id', ['google_id'], unique=False)
        batch_op.alter_column('isbn',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
