"""empty message

Revision ID: b502fd8a12c1
Revises: f520c7ef83b8
Create Date: 2023-11-04 12:10:20.733956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b502fd8a12c1'
down_revision = 'f520c7ef83b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=250), nullable=True))
        batch_op.drop_column('genres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', mysql.VARCHAR(length=250), nullable=True))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
