"""empty message

Revision ID: bb294fae1b95
Revises: 5b08a2b4e14c
Create Date: 2023-11-04 00:49:09.370057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb294fae1b95'
down_revision = '5b08a2b4e14c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.String(length=400),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###
