"""empty message

Revision ID: bbb098ff62aa
Revises: c8c73f4b76af
Create Date: 2023-11-06 20:52:29.858118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb098ff62aa'
down_revision = 'c8c73f4b76af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_best_seller', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('is_best_seller')

    # ### end Alembic commands ###
