"""empty message

Revision ID: ce2f56637491
Revises: 3f0656ed7dee
Create Date: 2023-12-03 23:33:13.646555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce2f56637491'
down_revision = '3f0656ed7dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_count', sa.Integer(), nullable=True))
        batch_op.drop_column('pages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pages', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('page_count')

    # ### end Alembic commands ###
