"""empty message

Revision ID: f520c7ef83b8
Revises: bb294fae1b95
Create Date: 2023-11-04 01:05:46.381873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f520c7ef83b8'
down_revision = 'bb294fae1b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.String(length=250), nullable=True))
        batch_op.alter_column('author',
               existing_type=mysql.VARCHAR(length=400),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', mysql.TEXT(), nullable=True))
        batch_op.alter_column('author',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=400),
               existing_nullable=False)
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
